dfdf

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,20 +46,21 @@ jobs:
 
       - name: Compare dates and sync if newer
         run: |
-          if [[ "$COMMIT_DATE" > "$LAST_UPDATED" ]]; then
+            if [[ "$COMMIT_DATE" > "$LAST_UPDATED" ]]; then
             echo "Changes detected. Syncing..."
-            rsync -avL --exclude='.github' --exclude='.git' parent-repo/"$SOURCE_FOLDER"/ ./ --delete || exit_code=$?
+
+            rsync -avL --copy-unsafe-links --exclude='.github' --exclude='.git' parent-repo/"$SOURCE_FOLDER"/ ./ --delete || exit_code=$?
             rm -rf parent-repo
             if [[ "$exit_code" != "" && "$exit_code" != "0" && "$exit_code" != "24" ]]; then
-              echo "rsync failed with exit code $exit_code"
-              exit $exit_code
+                echo "rsync failed with exit code $exit_code"
+                exit $exit_code
             fi
             echo "$COMMIT_DATE" > "$LAST_UPDATED_FILE"
             echo "SHOULD_COMMIT=true" >> $GITHUB_ENV
-          else
+            else
             echo "No changes detected."
             echo "SHOULD_COMMIT=false" >> $GITHUB_ENV
-          fi
+            fi
 
       - name: Commit and push if updated
         if: env.SHOULD_COMMIT == 'true'
